In [24]:
import pandas as pd
import numpy as np

In [65]:
df = pd.read_csv("C:/Users/Admin/Desktop/bits-AIML/machine_learning_practice_codes_github_folder/machine_learning/classification/Healthcare-Diabetes.csv")
df = df.drop(["Id"], axis =1)


# here we are trying to replace the 0 values or null values with mean
for column_name in df.columns:
    print(column_name)
    # print(df[f'{column_name}'].unique())
    if column_name != "Outcome":
        df[column_name].replace(to_replace = 0,value = None, inplace=True)
        mean = df[column_name].mean(skipna =True)
        df[column_name] = df[column_name].fillna(value = mean)


Pregnancies
Glucose
BloodPressure
SkinThickness
Insulin
BMI
DiabetesPedigreeFunction
Age
Outcome


C:\Users\Admin\AppData\Local\Temp\ipykernel_11720\1175273080.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column_name].replace(to_replace = 0,value = None, inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_11720\1175273080.py:12: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[column_name] =

In [66]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness    Insulin   BMI  \
0        6.000000    148.0           72.0      35.000000  154.23783  33.6   
1        1.000000     85.0           66.0      29.000000  154.23783  26.6   
2        8.000000    183.0           64.0      29.289634  154.23783  23.3   
3        1.000000     89.0           66.0      23.000000   94.00000  28.1   
4        4.397284    137.0           40.0      35.000000  168.00000  43.1   
...           ...      ...            ...            ...        ...   ...   
2763     2.000000     75.0           64.0      24.000000   55.00000  29.7   
2764     8.000000    179.0           72.0      42.000000  130.00000  32.7   
2765     6.000000     85.0           78.0      29.289634  154.23783  31.2   
2766     4.397284    129.0          110.0      46.000000  130.00000  67.1   
2767     2.000000     81.0           72.0      15.000000   76.00000  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.627   50        1  
1                        0.351   31        0  
2                        0.672   32        1  
3                        0.167   21        0  
4                        2.288   33        1  
...                        ...  ...      ...  
2763                     0.370   33        0  
2764                     0.719   36        1  
2765                     0.382   42        0  
2766                     0.319   26        1  
2767                     0.547   25        0  

[2768 rows x 9 columns]

In [67]:
from sklearn.model_selection import train_test_split

y = df.Outcome
x = df.drop('Outcome', axis = 1)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

In [68]:
# #importing the naive based classifier
# # Types of Naive Bayes Model
# # There are three types of Naive Bayes Model:

# # Gaussian Naive Bayes classifier
# # In Gaussian Naive Bayes, continuous values associated with each feature are assumed 
# # to be distributed according to a Gaussian distribution. 
# # A Gaussian distribution is also called Normal distribution When plotted, 
# # it gives a bell shaped curve which is symmetric about the mean of the feature values as shown below:

# Multinomial Naive Bayes
# Feature vectors represent the frequencies with which certain 
#     events have been generated by a multinomial distribution. This is the event model typically used for document classification.

# Bernoulli Naive Bayes
# In the multivariate Bernoulli event model, 
# features are independent booleans (binary variables) describing inputs. 
# Like the multinomial model, this model is popular for document classification tasks, 
# where binary term occurrence(i.e. a word occurs in a document or not) 
# features are used rather than term frequencies(i.e. frequency of a word in the document).

# multinomial navive bayes =  text based classification[ mostly used]
# bernoilu based = when we have more boolean kind of variables , use 
# gaussian - when we have more continuous kind of value in feature columns

In [69]:
from sklearn.naive_bayes import MultinomialNB

Multinomial = MultinomialNB()
Multinomial.fit(x_train, y_train)
y_pred = Multinomial.predict(x_test)
from sklearn.metrics import confusion_matrix


cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn import metrics
print("MultinomialNB Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)

[[410 135]
 [160 126]]
MultinomialNB Naive Bayes model accuracy(in %): 64.50060168471721


In [70]:
from sklearn.naive_bayes import BernoulliNB

Bernoulli = BernoulliNB()
Bernoulli.fit(x_train, y_train)
y_pred = Bernoulli.predict(x_test)
from sklearn.metrics import confusion_matrix


cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn import metrics
print("MultinomialNB Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)

[[545   0]
 [286   0]]
MultinomialNB Naive Bayes model accuracy(in %): 65.58363417569194


In [71]:
from sklearn.naive_bayes import GaussianNB

Gaussian = GaussianNB()
Gaussian.fit(x_train, y_train)
y_pred = Gaussian.predict(x_test)
from sklearn.metrics import confusion_matrix


cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn import metrics
print("MultinomialNB Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)

[[456  89]
 [127 159]]
MultinomialNB Naive Bayes model accuracy(in %): 74.0072202166065
